// <auto-generated />
using System;
using AeroElo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroElo.Api.Migrations
{
    [DbContext(typeof(AeroEloDbContext))]
    partial class AeroEloDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AeroElo.Api.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreB")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("AeroElo.Api.Models.MatchParticipant", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefenseEloChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EloChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffenseEloChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("AeroElo.Api.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BlueTeamLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlueTeamWins")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefenseElo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenseLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenseWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EloRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffenseElo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffenseLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffenseWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedTeamLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedTeamWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AeroElo.Api.Models.MatchParticipant", b =>
                {
                    b.HasOne("AeroElo.Api.Models.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AeroElo.Api.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
